// flow-typed signature: 63f3fe4c15ee12a1b0ec29b289605b01
// flow-typed version: <<STUB>>/classname_v^0.0.0/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'classname'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'classname' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'classname/classname' {
  declare module.exports: any;
}

declare module 'classname/spec/karma.conf' {
  declare module.exports: any;
}

declare module 'classname/spec/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'classname/classname.js' {
  declare module.exports: $Exports<'classname/classname'>;
}
declare module 'classname/spec/karma.conf.js' {
  declare module.exports: $Exports<'classname/spec/karma.conf'>;
}
declare module 'classname/spec/test.js' {
  declare module.exports: $Exports<'classname/spec/test'>;
}
