// flow-typed signature: 2a43a45d5629d977967b8c960f5e8f65
// flow-typed version: <<STUB>>/react-json-view_v^1.19.1/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-json-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-json-view/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-json-view/dist/main.js' {
  declare module.exports: $Exports<'react-json-view/dist/main'>;
}
