// flow-typed signature: e8e1f54306ba8d0caaa924ddf36c8148
// flow-typed version: <<STUB>>/schema-utils_v^2.5.0/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'schema-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'schema-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'schema-utils/dist' {
  declare module.exports: any;
}

declare module 'schema-utils/dist/keywords/absolutePath' {
  declare module.exports: any;
}

declare module 'schema-utils/dist/util/Range' {
  declare module.exports: any;
}

declare module 'schema-utils/dist/validate' {
  declare module.exports: any;
}

declare module 'schema-utils/dist/ValidationError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'schema-utils/dist/index' {
  declare module.exports: $Exports<'schema-utils/dist'>;
}
declare module 'schema-utils/dist/index.js' {
  declare module.exports: $Exports<'schema-utils/dist'>;
}
declare module 'schema-utils/dist/keywords/absolutePath.js' {
  declare module.exports: $Exports<'schema-utils/dist/keywords/absolutePath'>;
}
declare module 'schema-utils/dist/util/Range.js' {
  declare module.exports: $Exports<'schema-utils/dist/util/Range'>;
}
declare module 'schema-utils/dist/validate.js' {
  declare module.exports: $Exports<'schema-utils/dist/validate'>;
}
declare module 'schema-utils/dist/ValidationError.js' {
  declare module.exports: $Exports<'schema-utils/dist/ValidationError'>;
}
